// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://syxavayplxoobbbcitow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eGF2YXlwbHhvb2JiYmNpdG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MDIzOTgsImV4cCI6MjA5MTk3ODM5OH0.pM07-KCddEGtGDgk55LrHc1BpvW9LcbykVDQpTgZZSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);